services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=order_manager
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
