[package]
name = "task_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8.9", features = ["macros"] }
clap = { version = "4.6.1", features = ["derive", "env"] }
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_with = "3.20.0"
sqlx = { version = "0.8.6", features = [
  "macros",
  "derive",
  "postgres",
  "runtime-tokio",
  "tls-native-tls",
  "time",
] }
thiserror = "2.0.18"
time = { version = "0.3.47", features = ["serde"] }
tokio = { version = "1.52.3", features = ["full"] }
tower = "0.5.3"
tower-http = "0.6.10"
validator = { version = "0.20.0", features = ["derive"] }
